# Generated by Django 4.1 on 2024-11-10 04:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown name", max_length=255)),
                ("city", models.CharField(default="Unknown city", max_length=255)),
                ("region", models.CharField(default="Unknown region", max_length=255)),
                (
                    "cuisine",
                    models.CharField(default="Unknown cuisine", max_length=255),
                ),
                ("url", models.URLField(default="")),
                ("star_level", models.IntegerField(default=1)),
                ("year", models.IntegerField(default=2000)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        default="POINT(0 0)", srid=4326
                    ),
                ),
            ],
        ),
    ]
